# Generated by Django 5.1.4 on 2024-12-14 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='daily_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='todo.dailyuser'),
        ),
    ]
