# Generated by Django 5.1.4 on 2024-12-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_dailytask_daily_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
