# Generated by Django 4.2.3 on 2023-07-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_Management_App', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
