# Generated by Django 5.0.7 on 2024-10-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
