# Generated by Django 5.0.7 on 2024-10-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_order_phone_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='transaction_order',
        ),
    ]
