# Generated by Django 5.0.7 on 2024-11-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_order_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='price',
            new_name='sell_price',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='buy_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductBuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_buy_orders', to='product.product')),
            ],
            options={
                'db_table': 'product_buy_order',
            },
        ),
    ]
